### ISSUE TITLE
Sourcery Template not working

### ISSUE THREAD

**Issue by mergesort** [DroidsOnRoids/StructPersistence#1]
Hey Michał! Thanks so much for the guide, it's exactly what I'm looking to do right now until `Codable` becomes something we can use in Swift 4. Unfortunately I'm getting an error when running this through Sourcery, and was wondering what I was doing wrong. I copied the template exactly as is, and it's still not compiling. I've also tried fixing it up by replacing `typeName.name` (as the docs seem to dictate) with `type.name`, and `typeName`, and still no luck.

![sourcery](https://cloud.githubusercontent.com/assets/716513/26742834/5a9c4da6-47ad-11e7-9264-7c61664920b8.png)

I'd appreciate any help you can offer since this looks pretty great. Thanks!

**Comment by michaello** [comment]
Hey @mergesort ! I re-downloaded repo to check whether everything's fine, and my code generation passed with no problems. But I do have a sense what might've gone wrong in your case.
```for``` loop with ```where``` clause was added in [recent version of Stencil](https://github.com/kylef/Stencil/releases/tag/0.9.0). So maybe you're trying to run Sourcery with old version of Stencil. If you're coming from older repo or [Casey Liss tutorial](https://www.caseyliss.com/2017/3/31/the-magic-of-sourcery) (which inspired me to make this blogpost)!, then you might encounter this error.
Try to download the latest version of Sourcery(it's 0.6.1 now, I wrote blogpost when 0.6.0 was the latest one) which has newest ```where``` Stencil clause included.
 I would appreciate if you'd report back on whether it does the trick for you!

**Comment by mergesort** [comment]
That seems to have worked. I was on 0.6 and updating to 0.6.1 allowed it to compile.

It did create 2 issues unfortunately.

Optional types end up looking like this:
```swift
[QuizResponse?Coding]
```

Rather than:
```swift
[QuizResponseCoding?]
```

The other is 800+ warnings generated that look like this. 😢 
<img width="313" alt="warning" src="https://cloud.githubusercontent.com/assets/716513/26744874/ebc609b8-47b5-11e7-9242-d8e821033933.png">

Any thoughts on how to address those? Thanks a lot!

**Comment by michaello** [comment]
Hey @mergesort ,
Unfortunately I'm seeing this kind of problem for the first time 😢Surely templates in this project are not bulletproof for all types and structures, it's rather some starting point for creating own templates. But if you are able to send me a project or re-create this problem in a new one, then I'll try to check it out!

**Comment by mergesort** [comment]
I can ignore the 2nd one for now, and poke around with Sourcery itself, but something like this should be simple enough to recreate the first template issue.

```swift
public struct Test {
    public let id: Int
    public let testIds: [Int]?
}
```

**Comment by michaello** [comment]
Hmm, I tried on this example:

```swift
//sourcery: NSCodingWrapper
public struct Test {
    public let id: Int
    public let testIds: [Int]?
}
```

 and got:

```swift
// Generated using Sourcery 0.6.1 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

import Foundation

final class TestCoding: NSObject, NSCoding {

    fileprivate let test: Test

    init(test: Test) {
        self.test = test
        super.init()
    }

    required init?(coder aDecoder: NSCoder) {
        guard let testIds = aDecoder.decodeObject(forKey: "testIds") as? [Int]? else { return nil }
        test = Test(id: aDecoder.decodeInteger(forKey: "id"), testIds: testIds)
        super.init()
    }

    func encode(with aCoder: NSCoder) {
        aCoder.encode(test.id, forKey: "id")
        aCoder.encode(test.testIds, forKey: "testIds")
    }
}

extension TestCoding: StructRepresentable {
    var `struct`: Test {
        return test
    }
}

extension Test: Encoded {
    var encoder: TestCoding {
        return TestCoding(test: self)
    }
}
```

Am I something missing?

Thanks!

**Comment by mergesort** [comment]
Hey @michaello. Sorry for the delay, I was not working the last week. Upon further investigation what I posted does seem to work in isolation, so it looks like it must be something specific to my project. 🙁

I appreciate the time, and since it's not anything to do with your sample, I'll close my ticket and try to figure this out on my own. I greatly appreciate the time and energy you put into this, and thanks again!

**Comment by michaello** [comment]
No problem! Let me know when you have isolated problem in some sample project on GitHub. Cheers!
